<Project>
  <PropertyGroup>
    <Authors>vicmaeg</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/vicmaeg/ReleaseTools</PackageProjectUrl>
    <RepositoryUrl>https://github.com/vicmaeg/ReleaseTools.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>versioning;release;git;dotnet-tool</PackageTags>
    <PackAsTool>true</PackAsTool>
    <PackageDocumentationFile Condition="'$(MSBuildProjectName)' == 'semver.cs'">SemVer.md</PackageDocumentationFile>
    <PackageDocumentationFile Condition="'$(MSBuildProjectName)' == 'calver.cs'">CalVer.md</PackageDocumentationFile>
    <PackageDocumentationFile Condition="'$(MSBuildProjectName)' == 'scalver.cs'">ScalVer.md</PackageDocumentationFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(PackageDocumentationFile)' != ''">
    <None Include="$(MSBuildThisFileDirectory)../docs/$(PackageDocumentationFile)"
          Pack="true"
          PackagePath="$(PackageReadmeFile)" />
  </ItemGroup>
</Project>
