<Project>
  <PropertyGroup>
    <Authors>vicmaeg</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/vicmaeg/ReleaseTools</PackageProjectUrl>
    <RepositoryUrl>https://github.com/vicmaeg/ReleaseTools.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>versioning;release;git;dotnet-tool</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)../README.md"
          Pack="true"
          PackagePath="/"
          Link="README.md" />
  </ItemGroup>
</Project>
